# Generated by Django 2.1.5 on 2019-01-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operators',
            old_name='country',
            new_name='country_flag',
        ),
        migrations.AddField(
            model_name='operators',
            name='country_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
