# Generated by Django 2.1.5 on 2019-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='operator_description',
            field=models.TextField(blank=True),
        ),
    ]
