# Generated by Django 2.1.5 on 2019-01-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20190124_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_flag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='operators',
            name='country_flag',
        ),
        migrations.RemoveField(
            model_name='operators',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='operators',
            name='image',
        ),
        migrations.AddField(
            model_name='operators',
            name='operators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='mobile.Countries'),
            preserve_default=False,
        ),
    ]
