# Generated by Django 2.1.5 on 2019-01-25 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20190125_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operators',
            name='operators',
        ),
        migrations.AddField(
            model_name='countries',
            name='operators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='mobile.Operators'),
            preserve_default=False,
        ),
    ]
