# Generated by Django 2.1.5 on 2019-01-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20190125_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='operators',
        ),
        migrations.AddField(
            model_name='operators',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='mobile.Countries'),
            preserve_default=False,
        ),
    ]
