# Generated by Django 2.1.5 on 2019-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_auto_20190128_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
